import { Button, VerticalBox, StandardButton } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: ("Calculator");
    in-out property<float> total: 0; //total from past calculation initalized
    in-out property <float> digit: 0; //new digit entered to calculate
    in-out property <string> operation: ""; //saves operation type for calculation
    callback request-calc();
    VerticalBox {
        Text {
            text: "\{root.total}";
            font-size: 50px;
            width: 400px;
            height: 80px;
            }
            GridLayout {
                spacing: 5px;
                width: 400px;
                height: 150px;
                Row {
                    Button {text: 1; clicked => {if total == 0.0 { //fix for changing default value of total when a number is first entered
                        total = 1
                        }
                        else {
                            digit = digit * 10 + 1
                        }
                    }
                }
                    Button {text: 2; clicked => {if total == 0.0 {
                        total = 2
                        }
                        else {
                            digit = digit * 10 + 2
                        }
                    }
                }
                    Button {text: 3; clicked => {if total == 0.0 {
                        total = 3
                        }
                        else {
                            digit = digit * 10 + 3
                        }
                    }
                }
                    Button {text: "CE"; clicked => {total = 0} }
                }
                Row {
                    Button {text: 4; clicked => {if total == 0.0 {
                        total = 4
                        }
                        else {
                            digit = digit * 10 + 4
                        }
                    } 
                }
                    Button {text: 5; clicked => {if total == 0.0 {
                        total = 5
                        }
                        else {
                            digit = digit * 10 + 5
                        }
                    }
                }
                    Button {text: 6; clicked => {if total == 0.0 {
                        total = 6
                        }
                        else {
                            digit = digit * 10 + 6
                        }
                    }
                }
                    Button {text: "-"; clicked => {operation = "-"}}
                }
                Row {
                    Button {text: 7; clicked => {if total == 0.0 {
                        total = 7
                        }
                        else {
                            digit = digit * 10 + 7
                        }
                    }
                }
                    Button {text: 8; clicked => {if total == 0.0 {
                        total = 8
                        }
                        else {
                            digit = digit * 10 + 8
                        }
                    }
                }
                    Button {text: 9; clicked => {if total == 0.0 {
                        total = 9
                        }
                        else {
                            digit = digit * 10 + 9
                        }
                    }
                }
                    Button {text: "+"; clicked => {operation = "+"}}
                }
                Row {
                    Button {text: 0; clicked => {if total == 0.0 {
                        total = 0
                        }
                        else {
                            digit = digit * 10 + 0
                        }
                    }
                }
                    Button {text: "/"; clicked => {operation = "/"}}
                    Button {text: "="; clicked => {request-calc()} }
                    Button {text: "*"; clicked => {operation = "*"}}
                }
                Row {
                    Button {text: "(-)"; clicked => {digit = digit * -1}}
                }
            }    
        }
        
}